apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  namespace: app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
        - name: spark-master
          image: bitnami/spark:3.4.0
          ports:
            - containerPort: 7077
            - containerPort: 8080
          env:
            - name: SPARK_MODE
              value: "master"
            - name: SPARK_MASTER_HOST
              value: "0.0.0.0"
            - name: SPARK_MASTER_PORT
              value: "7078"
            - name: SPARK_MASTER_WEBUI_PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: spark-master
  namespace: app-namespace
spec:
  ports:
    - name: spark-cluster
      port: 7078
      targetPort: 7078
    - name: spark-webui
      port: 8082
      targetPort: 8080
  selector:
    app: spark-master