apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
  namespace: app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-worker
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      containers:
        - name: spark-worker
          image: bitnami/spark:3.4.0
          ports:
            - containerPort: 8081
          env:
            - name: SPARK_MODE
              value: "worker"
            - name: SPARK_MASTER_URL
              value: "spark://spark-master:7078"
            - name: SPARK_WORKER_PORT
              value: "7078"  # Worker port for cluster communication
            - name: SPARK_WORKER_WEBUI_PORT
              value: "8081"