apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
  namespace: app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: springboot-app
          image: springboot-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://mongodb:27017/streamingDB"
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-app
  namespace: app-namespace
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    app: springboot-app