apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: bitnami/zookeeper:latest
          ports:
            - containerPort: 2181
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: app-namespace
spec:
  ports:
    - name: zookeeper
      port: 2181
      targetPort: 2181
  selector:
    app: zookeeper